### ISSUE TITLE
CLI Version

### ISSUE THREAD

**Issue by SuperTavor** [Tiniifan/Pingouin#1]
Can you please add command line support? I just wanna extract the FA to a folder, edit it manually and repack it.

**Comment by Tiniifan** [comment]
No sorry I have no reason to make a CMD version, if you want a CMD Version you can do it by yourself

**Comment by SuperTavor** [comment]
if I make it and submit a pull request, will you merge it with the main branch?

**Comment by Tiniifan** [comment]
No
